services:
  your_service_name:
    build:
      dockerfile: ./docker-local/Dockerfile
      context: ../
    volumes:
      - ../:/usr/src/app
    container_name: your_service_name
    env_file: ../.env
    command: yarn start:dev
    environment:
      - PORT=3033
    ports:
      - 3033:3033
    depends_on:
      - postgres
    networks:
      - uponati-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3033/healthy']
      interval: 10s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer1234
    ports:
      - 5432:5432
    volumes:
      - uponati-db-volume:/var/lib/postgresql/data
    networks:
      - uponati-network

networks:
  uponati-network:
    driver: bridge

volumes:
  uponati-db-volume:
    driver: local
